# cmd: conda build . -c conda-forge
package:
    name: autoio-base
    version: "0.9.5"

source:
    path: .

requirements:
    host:
        - conda-forge::python=3.10
    run:
        - conda-forge::python=3.10
        - conda-forge::numpy
        - conda-forge::scipy
        - conda-forge::more-itertools
        - conda-forge::pyyaml
        - conda-forge::mako
        - conda-forge::pytest
        - conda-forge::pytest-cov
        - conda-forge::future
        - conda-forge::flake8
        - conda-forge::pylint
        - conda-forge::qcelemental
        - conda-forge::pint==0.18
