name: build

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      # Repository
      - name: Checkout the code
        uses: actions/checkout@v4

      # Environment
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.9

      # Build
      - name: Build
        run: |
          pixi build

      # Upload
      - name: Upload
        if: ${{ github.ref_name == 'dev' && github.repository_owner == 'Auto-Mech'}}
        run: |
          pixi run -e build upload
        env:
          ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_KEY }}
        continue-on-error: true
